<map>
	<line:{1}><space:{3}/>/<rm_width:{0}/>|</line:{1}>
	<line:{2}><space:{2}/>/<rm_width:{1}/>|</line:{2}>
	<line:{3}><space:{1}/>/<rm_width:{1}/>|</line:{3}>
	<line:{4}><space:{0}/>/<rm_width:{1}/>|</line:{4}>
	<line:{5}><space:{0}/>|<rm_width:{1}/>|</line:{5}>
	<line:{6}><space:{t}/><new_map:{new_map}/></line:{6}>
	<line:{7}><space:{t}/><load_map:{load_map}/></line:{7}>
	<line:{8}><space:{t}/><mods:{mods}/></line:{8}>
	<line:{9}><space:{t}/><options:{options}/></line:{9}>
	<line:{10}><space:{t}/><esc:{backspace}/></line:{10}>
</map>
